package com.example.pabproject.ui.screens

import android.widget.Toast
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Info
import androidx.compose.material.icons.filled.QrCode
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavController
import com.example.pabproject.LocalHistoryManager
import com.example.pabproject.ui.components.*
import com.example.pabproject.ui.theme.AbrilFatface
import com.example.pabproject.ui.theme.Nunito
import com.example.pabproject.ui.theme.PlayfairDisplay
import com.example.pabproject.utils.QRCodeGenerator
import com.example.pabproject.viewmodel.MainViewModel
import com.example.pabproject.viewmodel.MainViewModelFactory
import androidx.lifecycle.SavedStateHandle

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SmsToQRScreen(
    navController: NavController,
    viewModel: MainViewModel = viewModel(
        factory = MainViewModelFactory(SavedStateHandle())
    )
) {
    val phoneNumber by viewModel.phoneNumber.collectAsState()
    val smsMessage by viewModel.smsMessage.collectAsState()
    val isQrGenerated by viewModel.isQrGenerated.collectAsState()
    val errorMessage by viewModel.errorMessage.collectAsState()
    
    val scrollState = rememberScrollState()
    val context = LocalContext.current
    val historyManager = LocalHistoryManager.current
    val currentRoute = navController.currentDestination?.route
    
    // Show error message if any
    LaunchedEffect(errorMessage) {
        errorMessage?.let {
            Toast.makeText(context, it, Toast.LENGTH_SHORT).show()
        }
    }
    
    Scaffold(
        topBar = {
            TopAppBar(
                title = { 
                    Text(
                        "SMS to QR Code",
                        fontFamily = PlayfairDisplay,
                        fontWeight = FontWeight.Bold,
                        fontSize = 18.sp,
                        color = MaterialTheme.colorScheme.primary
                    ) 
                },
                navigationIcon = {
                    IconButton(onClick = { navController.popBackStack() }) {
                        Icon(
                            Icons.AutoMirrored.Filled.ArrowBack, 
                            contentDescription = "Back",
                            tint = MaterialTheme.colorScheme.primary
                        )
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.7f)
                )
            )
        },
        bottomBar = {
            BottomNavigationBar(navController, currentRoute)
        },
        containerColor = MaterialTheme.colorScheme.background
    ) { innerPadding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
                .padding(16.dp)
                .verticalScroll(scrollState),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.spacedBy(24.dp)
        ) {
            Text(
                text = "Generate SMS QR Code",
                fontFamily = AbrilFatface,
                fontWeight = FontWeight.Normal,
                fontSize = 24.sp,
                letterSpacing = 0.25.sp,
                color = MaterialTheme.colorScheme.primary
            )
            
            FormContainer(title = "SMS Details") {
                QRTextField(
                    value = phoneNumber,
                    onValueChange = { 
                        viewModel.setPhoneNumber(it)
                    },
                    placeholder = "Phone Number",
                    keyboardType = KeyboardType.Phone,
                    singleLine = true
                )
                
                Spacer(modifier = Modifier.height(8.dp))
                
                QRTextField(
                    value = smsMessage,
                    onValueChange = { 
                        viewModel.setSmsMessage(it)
                    },
                    placeholder = "Message (Optional)",
                    keyboardType = KeyboardType.Text,
                    singleLine = false,
                    minLines = 3,
                    maxLines = 6
                )
                
                Spacer(modifier = Modifier.height(16.dp))
                
                QRActionButton(
                    text = "Generate QR Code",
                    icon = Icons.Default.QrCode,
                    onClick = {
                        viewModel.generateQrCode("SMS")
                        if (phoneNumber.isNotBlank()) {
                            val smsContent = buildString {
                                append("smsto:$phoneNumber")
                                if (smsMessage.isNotBlank()) append(":${smsMessage}")
                            }
                            historyManager.addHistoryItem("SMS QR", smsContent)
                        }
                    },
                    enabled = phoneNumber.isNotBlank(),
                    modifier = Modifier.fillMaxWidth(),
                    isPrimary = true
                )
            }
            
            SuccessMessage(
                message = "QR Code generated and saved to history!",
                isVisible = isQrGenerated
            )
            
            if (phoneNumber.isNotBlank() && isQrGenerated) {
                val smsContent = buildString {
                    append("smsto:$phoneNumber")
                    if (smsMessage.isNotBlank()) append(":${smsMessage}")
                }
                QRCodeDisplay(
                    text = smsContent,
                    modifier = Modifier.size(220.dp)
                )
                
                // Info card about scanning functionality
                Card(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(top = 16.dp),
                    colors = CardDefaults.cardColors(
                        containerColor = MaterialTheme.colorScheme.secondaryContainer.copy(alpha = 0.7f)
                    )
                ) {
                    Row(
                        modifier = Modifier.padding(16.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Icon(
                            imageVector = Icons.Default.Info,
                            contentDescription = "Information",
                            tint = MaterialTheme.colorScheme.onSecondaryContainer
                        )
                        
                        Spacer(modifier = Modifier.width(12.dp))
                        
                        Text(
                            text = "When this QR code is scanned, it will automatically open the SMS app with the phone number and message pre-filled.",
                            fontFamily = Nunito,
                            fontSize = 14.sp,
                            lineHeight = 20.sp,
                            color = MaterialTheme.colorScheme.onSecondaryContainer,
                            modifier = Modifier.fillMaxWidth()
                        )
                    }
                }
            }
            
            Spacer(modifier = Modifier.height(40.dp))
        }
    }
} 