package com.example.pabproject.ui.screens

import android.widget.Toast
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.QrCode
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavController
import com.example.pabproject.LocalHistoryManager
import com.example.pabproject.ui.components.*
import com.example.pabproject.ui.theme.AbrilFatface
import com.example.pabproject.ui.theme.PlayfairDisplay
import com.example.pabproject.viewmodel.MainViewModel
import com.example.pabproject.viewmodel.MainViewModelFactory
import androidx.lifecycle.SavedStateHandle

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun URLToQRScreen(
    navController: NavController,
    viewModel: MainViewModel = viewModel(
        factory = MainViewModelFactory(SavedStateHandle())
    )
) {
    val urlContent by viewModel.urlContent.collectAsState()
    val isQrGenerated by viewModel.isQrGenerated.collectAsState()
    val errorMessage by viewModel.errorMessage.collectAsState()
    val qrColor by viewModel.qrColor.collectAsState()
    val backgroundColor by viewModel.backgroundColor.collectAsState()
    
    val scrollState = rememberScrollState()
    val context = LocalContext.current
    val historyManager = LocalHistoryManager.current
    val currentRoute = navController.currentDestination?.route
    
    // Show error message if any
    LaunchedEffect(errorMessage) {
        errorMessage?.let {
            Toast.makeText(context, it, Toast.LENGTH_SHORT).show()
        }
    }
    
    Scaffold(
        topBar = {
            TopAppBar(
                title = { 
                    Text(
                        "URL to QR Code",
                        fontFamily = PlayfairDisplay,
                        fontWeight = FontWeight.Bold,
                        fontSize = 18.sp,
                        color = MaterialTheme.colorScheme.primary
                    ) 
                },
                navigationIcon = {
                    IconButton(onClick = { navController.popBackStack() }) {
                        Icon(
                            Icons.AutoMirrored.Filled.ArrowBack, 
                            contentDescription = "Back",
                            tint = MaterialTheme.colorScheme.primary
                        )
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.7f)
                )
            )
        },
        bottomBar = {
            BottomNavigationBar(navController, currentRoute)
        },
        containerColor = MaterialTheme.colorScheme.background
    ) { innerPadding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
                .padding(16.dp)
                .verticalScroll(scrollState),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.spacedBy(24.dp)
        ) {
            Text(
                text = "Generate URL QR Code",
                fontFamily = AbrilFatface,
                fontWeight = FontWeight.Normal,
                fontSize = 24.sp,
                letterSpacing = 0.25.sp,
                color = MaterialTheme.colorScheme.primary
            )
            
            FormContainer(title = "Enter URL") {
                QRTextField(
                    value = urlContent,
                    onValueChange = { 
                        viewModel.setUrlContent(it)
                    },
                    placeholder = "Enter website URL (e.g., https://www.example.com)",
                    keyboardType = KeyboardType.Uri,
                    singleLine = true
                )
                
                Spacer(modifier = Modifier.height(8.dp))
                
                QRActionButton(
                    text = "Generate QR Code",
                    icon = Icons.Default.QrCode,
                    onClick = {
                        viewModel.generateQrCode("URL")
                        if (urlContent.isNotBlank()) {
                            historyManager.addHistoryItem(
                                type = "URL QR", 
                                content = urlContent,
                                qrColor = Color(qrColor),
                                backgroundColor = Color(backgroundColor)
                            )
                        }
                    },
                    enabled = urlContent.isNotBlank(),
                    modifier = Modifier.fillMaxWidth(),
                    isPrimary = true
                )
            }
            
            // Advanced Color Picker
            AdvancedColorPicker(
                selectedColor = Color(qrColor),
                selectedBackgroundColor = Color(backgroundColor),
                customColorManager = viewModel.customColorManager,
                onColorSelected = { color ->
                    viewModel.setQrColor(color)
                },
                onBackgroundColorSelected = { color ->
                    viewModel.setBackgroundColor(color)
                },
                modifier = Modifier.fillMaxWidth()
            )

            SuccessMessage(
                message = "QR Code generated and saved to history!",
                isVisible = isQrGenerated
            )
            
            if (urlContent.isNotBlank() && isQrGenerated) {
                QRCodeDisplay(
                    text = urlContent,
                    qrColor = Color(qrColor),
                    backgroundColor = Color(backgroundColor),
                    modifier = Modifier.size(220.dp)
                )
            }
            
            Spacer(modifier = Modifier.height(40.dp))
        }
    }
} 